version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

    # Un-comment to disable all pull requests for Docker dependencies
    # open-pull-requests-limit: 0
