version: "3.7"

services:
  # sut Automated Repository Test
  # see https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    # Running /usr/bin/nmap "-V" will print the installed version number and exit
    command: -V
