name: cd

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - ".editorconfig"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - ".editorconfig"
  schedule:
    - cron: "3 1 * * SUN" # every Sunday at 1:03 AM UTC
  workflow_dispatch:

jobs:
  push:
    name: Push to Docker Hub
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: jonlabelle/nmap:latest
