name: ghcr prune

on:
  push:
  schedule:
    - cron: "13 9 * * *" # Every day at 9:13 AM UTC

jobs:
  prune:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement scripts/ghcr-prune-requirements.txt

      - name: Prune all untagged images
        run: python scripts/ghcr-prune.py --container network-tools --prune-all-untagged --verbose
